apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-win
spec:
  provider: azure
  secretObjects: # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
    - data:
        - key: DB_HOST
          objectName: DB_HOST # name of the mounted content to sync. this could be the object name or object alias
        - key: DB_NAME
          objectName: DB_NAME
        - key: DB_PASSWORD
          objectName: DB_PASSWORD
        - key: DB_PORT
          objectName: DB_PORT
        - key: DB_USER
          objectName: DB_USER
      secretName: akvsecretscertwin
      type: Opaque

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "b9cbb22f-16df-4d43-8f7f-4f97ffdd343e" #assign identity client_id
    keyvaultName: poll-keyvault # the name of the KeyVault
    cloudName: AzurePublicCloud # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: DBHost
          objectAlias: DB_HOST
          objectType: secret
          objectVersion: ""
        - |
          objectName: DBName
          objectAlias: DB_NAME
          objectType: secret
          objectVersion: ""
        - |
          objectName: DBPassword
          objectAlias: DB_PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: DBPort
          objectAlias: DB_PORT
          objectType: secret
          objectVersion: ""
        - |
          objectName: DBUser
          objectAlias: DB_USER
          objectType: secret
          objectVersion: ""
    resourceGroup: "poll-rg" #provide azure key vault resourceGroup
    subscriptionId: "97bc8f84-568f-4b16-a365-14ffad56d435" # subscriptionId
    tenantId: "fa0fd8d2-d414-482c-a2a3-d86969b5c5fc" # TenantId
